development:
    dialect: mysql
    dir: sql/migrations
    datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:3306)/geo?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true&multiStatements=true

