version: '3'

services:
  dev:
    build: .
    user: "${UID_GID:-1000:1000}"
    environment:
      - MYSQL_USER=geouser
      - MYSQL_PASSWORD=mysql
      - MYSQL_HOST=db
    volumes:
      - ./:/workspace
    networks:
      - db-network
    entrypoint: ["tail", "-f", "/dev/null"]

  db:
    image: mysql:8.0.28
    ports:
      - 3306:3306
    user: "${UID_GID:-1000:1000}"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=geouser
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-pmysql", "-e", "SELECT NOW()"]
      interval: 5s
      timeout: 5s
      retries: 5      

networks:
  db-network:
    driver: bridge
